# Generated by Django 5.2 on 2025-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_media_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name="Domaine d'activité")),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('video_file', models.CharField(max_length=500, verbose_name='Chemin du fichier vidéo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom original du fichier')),
                ('file_size', models.BigIntegerField(verbose_name='Taille du fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vidéo active')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
