# Generated by Django 5.2.1 on 2025-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('domaine', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
