# Generated by Django 5.2 on 2025-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprises',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AddField(
            model_name='entreprises',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
